version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rp123456789
      MYSQL_DATABASE: socialmedia
      MYSQL_USER: chan
      MYSQL_PASSWORD: chan1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
